server:
  port: 8083

spring:
  application:
    name: store-service
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:agrigo_store;DB_CLOSE_DELAY=-1;MODE=MySQL}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  h2:
    console:
      enabled: true
